/* ============================================================
   English Lab — shared data (words, articles, collocations)
   Loaded before lab-core.js and each page's script.
   ============================================================ */

/* ============ VERİ ============ */
const WORDS = [
  {en:`slit`, tr:`yarık, ince kesik`, type:`kelime`, uk:`/slɪt/`, us:`/slɪt/`, note:`Eski İngilizce "slitan" (yarmak, yırtmak) fiilinden gelir; "split" ile akrabadır.`, detail:`Uzun, ince bir kesik ya da aralık. Hem "yarık açmak" fiili hem de "ince aralık" ismi olarak kullanılır.`, ex:`She peered through a slit in the curtains.`, exTr:`Perdedeki ince bir yarıktan dışarıyı gözetledi.`, ex2:`He made a small slit in the envelope with a knife.`, exTr2:`Zarfta bıçakla küçük bir yarık açtı.`, similar:`slot, crack, gap. Fark: slit uzun ve incedir; slot belli bir amaç için açılmış düzgün yuvadır (ör. para yuvası); crack çatlaktır; gap genel bir boşluktur.`, coll:`a slit IN sth (curtain, envelope) · peer/look THROUGH a slit · MAKE a slit`},
  {en:`gill`, tr:`solungaç`, type:`kelime`, uk:`/ɡɪl/`, us:`/ɡɪl/`, note:`Muhtemelen İskandinav kökenli (Eski Norsça). Mantar şapkasının altındaki ince lamellere de "gills" denir.`, detail:`Balıkların sudan oksijen aldığı solunum organı.`, ex:`Fish extract oxygen from water through their gills.`, exTr:`Balıklar sudan oksijeni solungaçları aracılığıyla alır.`, ex2:`The shark's gills flared as it swam.`, exTr2:`Köpekbalığı yüzerken solungaçları açıldı.`, coll:`breathe/extract oxygen THROUGH the gills · a fish's gills · gills flared`},
  {en:`eerie`, tr:`ürkütücü, tekinsiz`, type:`sıfat`, uk:`/ˈɪəri/`, us:`/ˈɪri/`, note:`Kuzey İngiltere ve İskoç lehçesinden; ilk anlamı "korku dolu" idi.`, detail:`Tuhaf ve gizemli bir biçimde korkutucu; insanın tüylerini ürperten.`, ex:`An eerie silence filled the abandoned house.`, exTr:`Terk edilmiş evi tekinsiz bir sessizlik kapladı.`, ex2:`There was something eerie about the old doll.`, exTr2:`Eski oyuncak bebekte tekinsiz bir şey vardı.`, similar:`creepy, spooky, uncanny. Fark: eerie sessiz ve gizemli bir ürperti verir; creepy tüyler ürperticidir; spooky hayaletimsidir; uncanny tuhaf biçimde tanıdıktır.`, opposite:`ordinary, reassuring.`, coll:`an eerie silence/feeling/glow · there was something eerie ABOUT sth`},
  {en:`hiccough`, tr:`hıçkırık; (mecazi) ufak aksaklık`, type:`kelime`, uk:`/ˈhɪkʌp/`, us:`/ˈhɪkʌp/`, note:`Sesi taklit eden bir sözcüktür.`, detail:`Diyaframın istemsiz kasılması; mecazi olarak küçük, geçici bir aksaklık.`, ex:`The launch went smoothly apart from one small hiccough.`, exTr:`Lansman, küçük bir aksaklık dışında sorunsuz geçti.`, ex2:`I got the hiccoughs after eating too fast.`, exTr2:`Çok hızlı yiyince hıçkırık tuttu.`, extra:`"hiccup" ile aynı kelimedir; bu eski yazım, "cough" (öksürük) sözcüğüne yanlış benzetmeyle oluşmuştur ama okunuşu değişmez.`, coll:`GET/HAVE the hiccoughs · a small/minor hiccough (aksaklık için)`},
  {en:`burden`, tr:`yük, külfet`, type:`kelime`, uk:`/ˈbɜːdn/`, us:`/ˈbɜːrdn/`, note:`Eski İngilizce "byrþen"; "bear" (taşımak) fiiliyle akrabadır.`, detail:`Ağır bir yük; kişiyi kaygılandıran bir görev ya da sorumluluk.`, ex:`The cost of care placed a huge burden on the family.`, exTr:`Bakım masrafı aileye büyük bir yük bindirdi.`, ex2:`She didn't want to be a burden to anyone.`, exTr2:`Kimseye yük olmak istemiyordu.`, similar:`load, weight, onus. Fark: burden hem fiziksel hem manevi ağırlıktır; load somut yüktür; onus resmi dilde sorumluluk yüküdür.`, opposite:`relief, boon.`, coll:`PLACE/PUT a burden ON sb · a burden TO sb · CARRY/EASE the burden`},
  {en:`greedy`, tr:`açgözlü`, type:`sıfat`, uk:`/ˈɡriːdi/`, us:`/ˈɡriːdi/`, note:`Eski İngilizce "grædig" sözcüğünden.`, detail:`İhtiyacından fazla yemek, para ya da güç isteyen.`, ex:`He was too greedy to share the prize.`, exTr:`Ödülü paylaşamayacak kadar açgözlüydü.`, ex2:`Don't be greedy; leave some cake for the others.`, exTr2:`Açgözlülük etme, başkalarına da biraz pasta bırak.`, similar:`avaricious, gluttonous, grasping. Fark: greedy geneldir; gluttonous özellikle yemekte oburluktur; avaricious ve grasping parada aşırılıktır.`, opposite:`generous, unselfish.`, coll:`greedy FOR sth · too greedy TO do sth · don't be greedy`},
  {en:`curbside`, tr:`kaldırım kenarı, yol kenarı`, type:`kelime`, uk:`/ˈkɜːbsaɪd/`, us:`/ˈkɜːrbsaɪd/`, note:`"curb" (kaldırım kenarı, İngiliz yazımıyla "kerb") + "side". Özellikle araçtan inmeden teslim almada kullanılır.`, detail:`Yolun ya da kaldırımın kenarı; "curbside pickup" araçtan inmeden teslim alma demektir.`, ex:`You can collect your order at curbside.`, exTr:`Siparişini yol kenarından, arabandan inmeden alabilirsin.`, ex2:`The taxi waited at the curbside.`, exTr2:`Taksi yol kenarında bekledi.`, coll:`AT the curbside · curbside pickup/collection · wait at the curbside`},
  {en:`detached house`, tr:`müstakil ev`, type:`kalıp`, uk:`/dɪˌtætʃt ˈhaʊs/`, us:`/dɪˌtætʃt ˈhaʊs/`, note:`"detached" Fransızca "détacher" (ayırmak) fiilinden. Karşıtı "semi-detached" (ikiz/bitişik) evdir.`, detail:`Başka hiçbir binaya bitişik olmayan, tek başına duran ev.`, ex:`They bought a detached house with a large garden.`, exTr:`Büyük bahçeli, müstakil bir ev aldılar.`, ex2:`Detached houses are more expensive than flats here.`, exTr2:`Burada müstakil evler dairelerden daha pahalı.`, coll:`a detached house WITH a garden · BUY/LIVE IN a detached house`},
  {en:`eyelid`, tr:`göz kapağı`, type:`kelime`, uk:`/ˈaɪlɪd/`, us:`/ˈaɪlɪd/`, note:`"eye" (göz) + "lid" (kapak, Eski İngilizce "hlid").`, detail:`Gözü örten, açılıp kapanan ince deri kıvrımı.`, ex:`Her eyelids grew heavy as she read.`, exTr:`Okurken göz kapakları ağırlaştı.`, ex2:`A tiny insect landed on his eyelid.`, exTr2:`Minik bir böcek göz kapağına kondu.`, coll:`eyelids grew heavy · sth landed ON one's eyelid · droopy/heavy eyelids`},
  {en:`nod`, tr:`baş sallamak (onaylama)`, type:`kelime`, uk:`/nɒd/`, us:`/nɑːd/`, note:`Orta İngilizce kökenli, kesin kaynağı belirsiz.`, detail:`Onaylamak ya da selamlamak için başı aşağı yukarı hareket ettirmek.`, ex:`She gave a slight nod to show she understood.`, exTr:`Anladığını göstermek için hafifçe başını salladı.`, ex2:`He nodded off during the lecture.`, exTr2:`Ders sırasında uyuyakaldı.`, extra:`"nod off" kalıbı, oturduğun yerde uyuyakalmak demektir.`, coll:`GIVE a nod · nod (one's head) TO/AT sb · nod OFF (uyuyakalmak)`},
  {en:`absence`, tr:`yokluk; (bir yerde) bulunmama`, type:`kelime`, uk:`/ˈæbsəns/`, us:`/ˈæbsəns/`, note:`Latince "absentia" sözcüğünden.`, detail:`Bir yerde bulunmama hali; bir şeyin eksikliği.`, ex:`In the absence of evidence, the case was dropped.`, exTr:`Kanıt yokluğunda dava düştü.`, ex2:`Her absence from the meeting was noticed.`, exTr2:`Toplantıdaki yokluğu fark edildi.`, similar:`lack, dearth, want. Fark: absence bir şeyin ya da kişinin hiç olmamasıdır; lack yetersizliktir; dearth kıtlık derecesinde azlıktır.`, opposite:`presence.`, coll:`IN the absence OF sth · absence FROM (a meeting) · in sb's absence`},
  {en:`valuable`, tr:`değerli, kıymetli`, type:`sıfat`, uk:`/ˈvæljuəbl/`, us:`/ˈvæljəbl/`, note:`"value" (değer) sözcüğünden; Latince "valere" (değmek, güçlü olmak) fiilinden.`, detail:`Çok para eden ya da çok işe yarayan.`, ex:`Your feedback has been extremely valuable.`, exTr:`Geri bildirimin son derece değerliydi.`, ex2:`The museum houses many valuable paintings.`, exTr2:`Müze pek çok değerli tabloya ev sahipliği yapıyor.`, similar:`precious, priceless, worthwhile. Fark: valuable değerlidir; precious duygusal ya da nadir değeri vurgular; priceless paha biçilmezdir; worthwhile çabaya değerdir.`, opposite:`worthless, valueless.`, coll:`extremely/highly valuable · valuable TO sb · a valuable lesson/asset`},
  {en:`irreplaceable`, tr:`yeri doldurulamaz, eşsiz`, type:`sıfat`, uk:`/ˌɪrɪˈpleɪsəbl/`, us:`/ˌɪrɪˈpleɪsəbl/`, note:`"ir-" (olumsuzluk) + "replace" (değiştirmek) + "-able".`, detail:`Yerine bir başkası konulamayacak kadar özel ya da benzersiz.`, ex:`These old photographs are irreplaceable.`, exTr:`Bu eski fotoğrafların yeri doldurulamaz.`, ex2:`A good mentor is irreplaceable.`, exTr2:`İyi bir mentorun yeri doldurulamaz.`, similar:`unique, one-of-a-kind. Fark: irreplaceable yeri doldurulamaz olandır; unique benzersizdir ama illa değerli değildir.`, opposite:`replaceable, expendable.`, coll:`utterly/truly irreplaceable · an irreplaceable asset/part of the team`},
  {en:`clandestine`, tr:`gizli, el altından`, type:`sıfat`, uk:`/klænˈdestɪn/`, us:`/klænˈdestən/`, note:`Latince "clandestinus"; "clam" (gizlice) kökünden.`, detail:`Özellikle izin verilmediği için gizli tutulan.`, ex:`They held clandestine meetings after dark.`, exTr:`Hava karardıktan sonra gizli toplantılar yaptılar.`, ex2:`The spy led a clandestine life for years.`, exTr2:`Casus yıllarca gizli bir hayat sürdü.`, similar:`covert, secret, surreptitious. Fark: clandestine ve covert gizli, izinsiz eylemler içindir (askeri, siyasi); secret geneldir; surreptitious sinsi, el çabukluğuyla yapılanı anlatır.`, opposite:`open, overt, aboveboard.`, coll:`HOLD clandestine meetings · a clandestine affair/operation/life`},
  {en:`pseudonym / pen name`, tr:`takma ad, müstear isim`, type:`kelime`, uk:`/ˈsjuːdənɪm/`, us:`/ˈsuːdənɪm/`, note:`Yunanca "pseudes" (sahte) + "onoma" (isim) sözcüklerinden.`, detail:`Bir yazarın gerçek adı yerine kullandığı uydurma isim.`, ex:`She wrote her thrillers under a pseudonym.`, exTr:`Gerilim romanlarını takma bir adla yazdı.`, ex2:`George Orwell was a pseudonym for Eric Blair.`, exTr2:`George Orwell, Eric Blair'in takma adıydı.`, extra:`"pen name" birebir "kalem adı" demektir.`, coll:`write UNDER a pseudonym/pen name · a pseudonym FOR sb`},
  {en:`bunker`, tr:`sığınak; (golf) kum çukuru`, type:`kelime`, uk:`/ˈbʌŋkə/`, us:`/ˈbʌŋkər/`, note:`İskoççada "bonker" (oturak, sandık); sonra kömürlük, ardından yeraltı sığınağı anlamını kazandı.`, detail:`Yeraltındaki korunaklı sığınak; golfte engel olarak konan kum çukuru.`, ex:`The troops took cover in an underground bunker.`, exTr:`Askerler yeraltındaki bir sığınağa saklandı.`, ex2:`His ball landed in the bunker beside the green.`, exTr2:`Topu, sahanın yanındaki kum çukuruna düştü.`, coll:`an underground bunker · TAKE cover/hide IN a bunker · land IN a bunker (golf)`},
  {en:`exasperated`, tr:`bıkkın, çileden çıkmış`, type:`sıfat`, uk:`/ɪɡˈzæspəreɪtɪd/`, us:`/ɪɡˈzæspəreɪtɪd/`, note:`Latince "exasperare" (pürüzlendirmek, kızdırmak); "asper" (pürüzlü) kökünden.`, detail:`Bir şeyden dolayı iyice sinirlenmiş ve bunalmış.`, ex:`She let out an exasperated sigh.`, exTr:`Bezgin bir iç çekiş saldı.`, ex2:`The teacher was exasperated by the constant noise.`, exTr2:`Öğretmen bitmeyen gürültüden bunalmıştı.`, hint:`Vurgu: bitmeyen bir şeyden bıkıp çileden çıkma.`, similar:`frustrated, irritated, aggravated. Fark: exasperated bıkkınlık ve çaresizliktir; frustrated engellenmişlik hissidir; irritated hafif sinirdir.`, opposite:`calm, content, unruffled.`, coll:`exasperated BY/WITH sb/sth · an exasperated sigh · GET exasperated`},
  {en:`commiserating`, tr:`(biriyle) dert ortağı olma, acısını paylaşma`, type:`kelime`, uk:`/kəˈmɪzəreɪtɪŋ/`, us:`/kəˈmɪzəreɪtɪŋ/`, note:`Latince "commiserari"; "com-" (birlikte) + "miser" (zavallı).`, detail:`Birinin talihsizliği karşısında ona acıyıp üzüntüsünü paylaşma.`, ex:`Friends gathered, commiserating with him over the loss.`, exTr:`Arkadaşları toplanıp kaybı için onunla dertleşti.`, ex2:`They spent the evening commiserating over lost jobs.`, exTr2:`Akşamı, kaybettikleri işler üzerine dertleşerek geçirdiler.`, coll:`commiserate WITH sb · commiserate OVER (a loss) · offer commiserations`},
  {en:`agitated`, tr:`tedirgin, huzursuz, telaşlı`, type:`sıfat`, uk:`/ˈædʒɪteɪtɪd/`, us:`/ˈædʒɪteɪtɪd/`, note:`Latince "agitare" (sürmek, hareket ettirmek) fiilinden.`, detail:`Sinirli, tedirgin, sakin duramayan.`, ex:`He became agitated when asked about the money.`, exTr:`Para sorulunca huzursuzlandı.`, ex2:`Don't get so agitated; we'll fix it.`, exTr2:`Bu kadar telaşlanma, hallederiz.`, hint:`Vurgu: tedirginlik ve telaşla yerinde duramama.`, similar:`anxious, restless, flustered. Fark: agitated dıştan görünen huzursuzluk ve hareketliliktir; anxious içsel kaygıdır; flustered şaşkın telaştır.`, opposite:`calm, composed, relaxed.`, coll:`GET/BECOME agitated · agitated ABOUT/BY sth · don't get so agitated`},
  {en:`perturbed`, tr:`tedirgin, huzuru kaçmış`, type:`sıfat`, uk:`/pəˈtɜːbd/`, us:`/pərˈtɜːrbd/`, note:`Latince "perturbare" (altüst etmek, karıştırmak) fiilinden.`, detail:`Kaygılı, kafası karışmış, huzuru kaçmış.`, ex:`She seemed perturbed by the sudden change of plan.`, exTr:`Ani plan değişikliğinden rahatsız olmuş görünüyordu.`, ex2:`He seemed deeply perturbed by the news.`, exTr2:`Haberden derin biçimde rahatsız olmuş görünüyordu.`, extra:`Karşıtı "unperturbed" (istifini bozmayan, sakin) de çok yaygındır.`, hint:`Vurgu: bir şeyin huzurunu kaçırması, kafasının karışması.`, similar:`unsettled, troubled, disconcerted. Fark: perturbed hafif, nazik bir rahatsızlıktır; troubled daha derin bir derttir; disconcerted afallamadır.`, opposite:`unperturbed, untroubled, calm.`, coll:`perturbed BY sth · deeply perturbed · seem perturbed (karşıtı unperturbed)`},
  {en:`ruthless`, tr:`acımasız, merhametsiz`, type:`sıfat`, uk:`/ˈruːθləs/`, us:`/ˈruːθləs/`, note:`Bugün tek başına kullanılmayan "ruth" (acıma, merhamet) + "-less". "ruth" artık eskimiş bir sözcüktür.`, detail:`Hiç merhamet göstermeyen.`, ex:`A ruthless dictator crushed all opposition.`, exTr:`Acımasız bir diktatör tüm muhalefeti ezdi.`, ex2:`She is ruthless in business negotiations.`, exTr2:`İş görüşmelerinde acımasızdır.`, hint:`Vurgu: acıma/merhamet yokluğu; hedefe giderken kimseyi kayırmama.`, similar:`cruel, merciless, heartless. Fark: ruthless hedefe giderken acımasızlıktır; merciless hiç af tanımaz; cruel acı çektirmeyi ister; heartless duygusuzdur.`, opposite:`merciful, compassionate.`, coll:`ruthless IN (business) · a ruthless dictator/pursuit · utterly ruthless`},
  {en:`cruel`, tr:`zalim, gaddar`, type:`sıfat`, uk:`/ˈkruːəl/`, us:`/ˈkruːəl/`, note:`Latince "crudelis"; "crudus" (çiğ, ham) ile akrabadır.`, detail:`Bilerek acı ya da ıstırap veren.`, ex:`It was cruel to leave the dog out in the cold.`, exTr:`Köpeği soğukta dışarıda bırakmak zalimceydi.`, ex2:`Fate can be cruel.`, exTr2:`Kader bazen zalim olabilir.`, hint:`Vurgu: kasten acı ve ıstırap çektirme; zalimlik.`, similar:`brutal, vicious, savage. Fark: cruel kasten acı verir; brutal kaba ve şiddetlidir; vicious kötücül saldırganlıktır; savage vahşidir.`, opposite:`kind, humane, gentle.`, coll:`cruel TO sb · it was cruel TO do sth · a cruel twist of fate`},
  {en:`blunt`, tr:`(bıçak) kör; (konuşma) dobra`, type:`sıfat`, uk:`/blʌnt/`, us:`/blʌnt/`, note:`Orta İngilizce; muhtemelen İskandinav kökenli.`, detail:`Keskin olmayan; ya da lafı yumuşatmadan, doğrudan söyleyen.`, ex:`To be blunt, your plan won't work.`, exTr:`Açık konuşayım, planın yürümez.`, ex2:`The knife was too blunt to cut the bread.`, exTr2:`Bıçak, ekmeği kesemeyecek kadar kördü.`, similar:`frank, curt, brusque. Fark: blunt lafı yumuşatmadan söyler (kırıcı olabilir); frank içten ve açıktır (nötr); curt ve brusque kısa, ters ve kabadır.`, opposite:`(söz) tactful, diplomatic; (bıçak) sharp.`, coll:`TO BE blunt · a blunt knife/instrument · blunt WITH sb · blunt ABOUT sth`},
  {en:`blunder`, tr:`gaf, büyük hata`, type:`kelime`, uk:`/ˈblʌndə/`, us:`/ˈblʌndər/`, note:`Orta İngilizce; "blind" (kör) sözcüğüyle akrabadır, "körü körüne davranmak" fikrini taşır.`, detail:`Dikkatsizce yapılan aptalca, büyük bir hata.`, ex:`Forgetting the client's name was a real blunder.`, exTr:`Müşterinin adını unutmak tam bir gaftı.`, ex2:`The general's blunder cost many lives.`, exTr2:`Generalin gafı birçok cana mal oldu.`, similar:`mistake, gaffe, slip-up. Fark: blunder dikkatsizce yapılan büyük hatadır; gaffe utandıran sosyal hatadır; slip-up küçük bir sürçmedir.`, coll:`MAKE a blunder · a costly/serious blunder · a tactical blunder`},
  {en:`hypocrite / hypocritical`, tr:`ikiyüzlü (kişi); ikiyüzlüce`, type:`kelime`, uk:`/ˈhɪpəkrɪt/ · /ˌhɪpəˈkrɪtɪkl/`, us:`/ˈhɪpəkrɪt/ · /ˌhɪpəˈkrɪtɪkl/`, note:`Yunanca "hypokrites" (oyuncu, rol yapan) sözcüğünden gelir. İkiyüzlü kişi de bir tür rol yapar.`, detail:`Sahip olmadığı ahlaki değerlere sahipmiş gibi davranan kişi ("hypocrite"); bu davranışın sıfatı "hypocritical".`, ex:`It's hypocritical to preach honesty while lying.`, exTr:`Yalan söylerken dürüstlük vaazı vermek ikiyüzlülüktür.`, ex2:`He called her a hypocrite for breaking her own rules.`, exTr2:`Kendi kurallarını çiğnediği için ona ikiyüzlü dedi.`, similar:`two-faced, phoney, sanctimonious. Fark: hypocrite savunduğu değerlere kendi uymayandır; two-faced yüze başka arkaya başka davranandır; sanctimonious sahte bir erdem gösterisidir.`, opposite:`sincere, genuine.`, coll:`CALL sb a hypocrite · it's hypocritical TO do sth · hypocritical ABOUT sth`},
  {en:`contradicting`, tr:`çelişen, ters düşen`, type:`kelime`, uk:`/ˌkɒntrəˈdɪktɪŋ/`, us:`/ˌkɑːntrəˈdɪktɪŋ/`, note:`Latince "contra" (karşı) + "dicere" (söylemek).`, detail:`Tam tersini söyleyen; kendisiyle ya da başka bir ifadeyle tutarsız.`, ex:`His statement kept contradicting the earlier report.`, exTr:`İfadesi, önceki raporla sürekli çelişiyordu.`, ex2:`You're contradicting yourself.`, exTr2:`Kendinle çelişiyorsun.`, opposite:`agreeing, corroborating, confirming.`, coll:`contradict yourself · keep contradicting (a report/statement) · directly contradict`},
  {en:`accountable`, tr:`hesap verebilir, sorumlu`, type:`sıfat`, uk:`/əˈkaʊntəbl/`, us:`/əˈkaʊntəbl/`, note:`"account" (hesap) sözcüğünden.`, detail:`Yaptıklarından sorumlu ve bunları açıklamakla yükümlü olan.`, ex:`Leaders must be held accountable for their decisions.`, exTr:`Liderler kararlarından dolayı hesap verebilir olmalıdır.`, ex2:`We hold ourselves accountable to our customers.`, exTr2:`Kendimizi müşterilerimize karşı sorumlu tutarız.`, similar:`responsible, liable, answerable. Fark: accountable hesap verme yükümlülüğüdür; responsible görev sahibidir; liable yasal olarak sorumludur.`, opposite:`unaccountable, unanswerable.`, coll:`HOLD sb accountable · accountable FOR sth · accountable TO sb`},
  {en:`rigged`, tr:`hileli, danışıklı, ayarlanmış`, type:`sıfat`, uk:`/rɪɡd/`, us:`/rɪɡd/`, note:`"rig" fiili önce "gemiyi donatmak" demekti; "hile ile ayarlamak" anlamı 19. yüzyılda çıktı.`, detail:`Belli bir sonucu vermek üzere hileyle düzenlenmiş.`, ex:`The protesters claimed the election was rigged.`, exTr:`Protestocular seçimin hileli olduğunu iddia etti.`, ex2:`He felt the whole system was rigged against him.`, exTr2:`Bütün sistemin ona karşı hileli kurulduğunu hissediyordu.`, opposite:`fair, aboveboard.`, coll:`a rigged election/game/system · rigged AGAINST sb · claim sth was rigged`},
  {en:`fake claims`, tr:`asılsız / sahte iddialar`, type:`kalıp`, uk:`/feɪk kleɪmz/`, us:`/feɪk kleɪmz/`, note:`"fake" 18. yüzyıl argosu; "claim" Latince "clamare" (haykırmak) fiilinden.`, detail:`Doğruymuş gibi sunulan yanlış iddialar.`, ex:`The ad was banned for making fake claims.`, exTr:`Reklam, asılsız iddialar öne sürdüğü için yasaklandı.`, ex2:`Beware of products with fake health claims.`, exTr2:`Sahte sağlık iddiaları taşıyan ürünlere dikkat et.`, coll:`MAKE fake claims · banned FOR making fake claims · fake health claims`},
  {en:`hoodwink`, tr:`kandırmak, aldatmak, göz boyamak`, type:`kelime`, uk:`/ˈhʊdwɪŋk/`, us:`/ˈhʊdwɪŋk/`, note:`Aslen "gözlerini bağlamak" demekti: "hood" (başlık) + "wink" (gözleri kapamak).`, detail:`Birini aldatmak, kandırmak.`, ex:`Investors were hoodwinked into a worthless scheme.`, exTr:`Yatırımcılar değersiz bir düzenle kandırıldı.`, ex2:`Don't let them hoodwink you with the fine print.`, exTr2:`Küçük puntolu yazılarla seni kandırmalarına izin verme.`, similar:`deceive, dupe, con, trick. Fark: hoodwink göz boyayarak kandırır; con çıkar için dolandırır; dupe saf birini kandırır; trick oyun oynar.`, coll:`hoodwink sb INTO (doing) sth · be hoodwinked BY sb · hoodwink sb WITH sth`},
  {en:`take a leaf out of someone's book`, tr:`birini örnek almak`, type:`deyim`, uk:``, us:``, note:`Buradaki "leaf", kitabın bir "yaprağı" (sayfası) demektir; yani "birinin sayfasından bir yaprak almak".`, detail:`Birinin iyi bir davranışını ya da yöntemini örnek alıp benzerini yapmak.`, ex:`You should take a leaf out of her book and start saving.`, exTr:`Onu örnek alıp sen de para biriktirmeye başlamalısın.`, ex2:`I took a leaf out of my mentor's book and started early.`, exTr2:`Mentorumu örnek alıp erken başladım.`, coll:`take a leaf OUT OF sb's book · you should take a leaf out of her book`},
  {en:`get someone back for something`, tr:`birinden acısını çıkarmak, öcünü almak`, type:`kalıp`, uk:``, us:``, note:`Günlük konuşmada intikam için kullanılan yaygın bir kalıptır.`, detail:`Birine yaptığı bir şeyin öcünü almak, misilleme yapmak.`, ex:`He keyed my car to get me back for the argument.`, exTr:`Tartışmanın acısını çıkarmak için arabamı çizdi.`, ex2:`She's just trying to get you back for last week.`, exTr2:`Sadece geçen haftanın acısını senden çıkarmaya çalışıyor.`, coll:`get sb back FOR sth · try to get sb back · just to get you back`},
  {en:`start a vendetta against`, tr:`birine karşı husumet / kan davası başlatmak`, type:`kalıp`, uk:``, us:``, note:`"vendetta" İtalyanca; Latince "vindicta" (öç) kökünden. Aslen aileler arası kan davasını anlatır.`, detail:`Birine karşı uzun süreli, hırslı bir intikam kampanyası başlatmak.`, ex:`The columnist started a vendetta against the mayor.`, exTr:`Köşe yazarı belediye başkanına karşı adeta husumet başlattı.`, ex2:`He seemed to start a vendetta against his old boss.`, exTr2:`Eski patronuna karşı adeta husumet başlatmış gibiydi.`, coll:`start/wage a vendetta AGAINST sb · a personal vendetta`},
  {en:`way below the belt`, tr:`(söz) çok ayıp, alçakça`, type:`deyim`, uk:``, us:``, note:`Boks kurallarından gelir: kemerin altına vurmak faul sayılır. "way" burada "çok, fazlasıyla" demektir.`, detail:`Bir sözün ya da davranışın haksız ve incitici derecede aşağılık olması.`, ex:`Mocking his stutter was way below the belt.`, exTr:`Kekemeliğiyle dalga geçmesi çok ayıptı, resmen kemerin altına vurmaktı.`, ex2:`Bringing up his divorce was way below the belt.`, exTr2:`Boşanmasını gündeme getirmesi çok ayıptı.`, coll:`way below the belt · hit/go below the belt · that was below the belt`},
  {en:`think it through`, tr:`iyice düşünüp taşınmak`, type:`kalıp`, uk:``, us:``, note:`"through" (baştan sona) burada işi eksiksiz düşünmeyi vurgular.`, detail:`Bir şeyi harekete geçmeden önce dikkatlice, tüm yönleriyle düşünmek.`, ex:`Don't rush; think it through first.`, exTr:`Acele etme; önce enine boyuna bir düşün.`, ex2:`Take a day and think it through before deciding.`, exTr2:`Karar vermeden önce bir gün ayır ve iyice düşün.`, coll:`think it through (FIRST) · take time to think it through · think sth through`},
  {en:`how is that news`, tr:`bunun neresi haber (bunda şaşılacak ne var)`, type:`kalıp`, uk:``, us:``, note:`Alaycı bir kalıptır: söylenen şeyin zaten bilindiğini, yeni bir şey olmadığını ima eder.`, detail:`"Bunu zaten herkes biliyor" demenin iğneleyici bir yolu.`, ex:`Traffic is bad on Mondays? How is that news?`, exTr:`Pazartesileri trafik kötüymüş, bunun neresi haber?`, ex2:`Politicians make promises? How is that news?`, exTr2:`Siyasetçiler söz mü veriyormuş, bunun neresi haber?`, coll:`How is that news? (alaycı, cümle sonunda soru olarak)`},
  {en:`deal with it`, tr:`idare et, başa çık; kabullen`, type:`kalıp`, uk:``, us:``, note:`Bağlama göre sert ("katlanacaksın") ya da nötr ("halledeceksin") tınlayabilir.`, detail:`Zorlu bir durumu kabullenip onunla baş etmek.`, ex:`The decision is final, so deal with it.`, exTr:`Karar kesin, o yüzden idare etmeye bak.`, ex2:`Life isn't fair; you just have to deal with it.`, exTr2:`Hayat adil değil, sadece idare etmek zorundasın.`, coll:`just deal with it · you'll have to deal with it · so deal with it`},
  {en:`preamble`, tr:`giriş, önsöz`, type:`kelime`, uk:`/ˈpriːæmbl/`, us:`/ˈpriːæmbl/`, note:`Latince "praeambulus" (önden yürüyen); "önden yürüme" fikrini taşır.`, detail:`Asıl konuya geçmeden önce yapılan giriş konuşması ya da metni.`, ex:`After a long preamble, she finally got to the point.`, exTr:`Uzun bir girişin ardından sonunda sadede geldi.`, ex2:`The contract's preamble states its purpose.`, exTr2:`Sözleşmenin girişi amacını belirtir.`, coll:`AFTER a long preamble · WITHOUT preamble · the preamble TO (a contract)`},
  {en:`indulgence`, tr:`kendini şımartma; hoşgörü, göz yumma`, type:`kelime`, uk:`/ɪnˈdʌldʒəns/`, us:`/ɪnˈdʌldʒəns/`, note:`Latince "indulgere" (hoş görmek, göz yummak) fiilinden.`, detail:`Kendine bir zevki fazlasıyla tanıma; ya da birine gösterilen hoşgörü, müsamaha.`, ex:`Chocolate is my one indulgence.`, exTr:`Çikolata, kendime tanıdığım tek keyiftir.`, ex2:`A weekend away was a rare indulgence for them.`, exTr2:`Bir hafta sonu kaçamağı onlar için nadir bir keyifti.`, similar:`treat, luxury, extravagance. Fark: indulgence kendine tanınan keyiftir; treat küçük bir ödüldür; luxury lükstür; extravagance savurganlıktır.`, opposite:`restraint, abstinence, moderation.`, coll:`my one indulgence · a rare/little indulgence · self-indulgence`},
  {en:`stagnant`, tr:`durgun; gelişmeyen, kımıldamayan`, type:`sıfat`, uk:`/ˈstæɡnənt/`, us:`/ˈstæɡnənt/`, note:`Latince "stagnare"; "stagnum" (durgun su birikintisi) kökünden.`, detail:`Akmayan, hareket etmeyen; ya da gelişmeyen, ilerlemeyen.`, ex:`Wages have been stagnant for a decade.`, exTr:`Maaşlar on yıldır durgun, hiç kıpırdamadı.`, ex2:`Mosquitoes breed in stagnant water.`, exTr2:`Sivrisinekler durgun suda ürer.`, similar:`stale, static, sluggish. Fark: stagnant akmayan ya da gelişmeyendir; stale bayat, tazeliğini yitirmiştir; static hiç değişmeyendir; sluggish ağır işleyendir.`, opposite:`flowing, dynamic, thriving.`, coll:`stagnant water · wages/growth remain stagnant · become stagnant`},
  {en:`detrimental`, tr:`zararlı, olumsuz`, type:`sıfat`, uk:`/ˌdetrɪˈmentl/`, us:`/ˌdetrɪˈmentl/`, note:`Latince "detrimentum" (kayıp, hasar) sözcüğünden.`, detail:`Bir şeye zarar veren, olumsuz etki eden.`, ex:`Smoking is detrimental to your health.`, exTr:`Sigara sağlığına zararlıdır.`, ex2:`Stress can be detrimental to sleep.`, exTr2:`Stres, uykuya zararlı olabilir.`, similar:`harmful, damaging, adverse. Fark: detrimental resmi dilde zararlıdır; harmful geneldir; adverse olumsuz etki ya da koşuldur.`, opposite:`beneficial, advantageous.`, coll:`detrimental TO (health/sleep) · have a detrimental effect ON sth`},
  {en:`moral fibre and merits`, tr:`ahlaki değerler ve erdemler`, type:`kalıp`, uk:``, us:``, note:`"moral fibre" karakterin iç gücü/dokusudur; "merits" ise değerli, takdire şayan yönler demektir.`, detail:`Bir kişinin ahlaki duruşu ile değerli, takdire değer yönleri.`, ex:`The role demands real moral fibre and clear merits.`, exTr:`Bu görev gerçek ahlaki değerler ve erdemler ister.`, ex2:`They judged him on his moral fibre and merits, not his wealth.`, exTr2:`Onu serveti üzerinden değil, ahlaki değerleri ve erdemleri üzerinden değerlendirdiler.`, coll:`moral fibre AND merits · judge sb ON their moral fibre and merits`},
  {en:`limelight`, tr:`ilgi odağı, gözler önünde olma`, type:`kelime`, uk:`/ˈlaɪmlaɪt/`, us:`/ˈlaɪmlaɪt/`, note:`19. yüzyıl tiyatrolarında sahne, kirecin (kalsiyum oksit) kızdırılmasıyla elde edilen parlak "lime light" ile aydınlatılırdı.`, detail:`Halkın ilgisinin, dikkatinin üzerinde toplandığı yer.`, ex:`After the win she enjoyed her time in the limelight.`, exTr:`Zaferden sonra ilgi odağı olmanın tadını çıkardı.`, ex2:`He shunned the limelight after retiring.`, exTr2:`Emekli olduktan sonra ilgi odağı olmaktan kaçındı.`, similar:`spotlight, fame, attention. Fark: limelight ve spotlight kamu ilgisinin odağıdır; fame ünün kendisidir; attention geneldir.`, opposite:`obscurity, anonymity.`, coll:`IN the limelight · STEAL/SHUN/HOG the limelight · step into the limelight`},
  {en:`share the limelight`, tr:`ilgiyi başkalarıyla paylaşmak`, type:`kalıp`, uk:``, us:``, note:`"limelight" (ilgi odağı) deyiminden türeyen bir kalıptır.`, detail:`Dikkatin, övgünün yalnız kendine kalmasına izin vermeyip başkalarına da pay bırakmak.`, ex:`A good captain shares the limelight with the team.`, exTr:`İyi bir kaptan, parlayan anı takımıyla paylaşır.`, ex2:`The star refused to share the limelight.`, exTr2:`Yıldız, ilgiyi paylaşmayı reddetti.`, coll:`share the limelight WITH sb · refuse to share the limelight`},
  {en:`tangled love lives`, tr:`karmakarışık aşk hayatları`, type:`kalıp`, uk:``, us:``, note:`"tangled" (düğüm olmuş, karışmış) sıfatı ilişkilerin içinden çıkılmaz haline gönderme yapar.`, detail:`İçinden çıkılmaz derecede karmaşık, dolaşık romantik ilişkiler.`, ex:`The show follows the tangled love lives of six friends.`, exTr:`Dizi, altı arkadaşın karmakarışık aşk hayatlarını konu alır.`, ex2:`Gossip columns thrive on celebrities' tangled love lives.`, exTr2:`Dedikodu köşeleri ünlülerin karmakarışık aşk hayatlarıyla beslenir.`, coll:`the tangled love lives OF (people) · follow their tangled love lives`},
  {en:`common ground`, tr:`ortak nokta, uzlaşma zemini`, type:`kalıp`, uk:``, us:``, note:`Birebir "ortak zemin"; iki tarafın da üzerinde durabileceği zemin imgesi.`, detail:`Anlaşmayı mümkün kılan paylaşılan ilgi ya da görüşler.`, ex:`The two parties finally found common ground.`, exTr:`İki taraf sonunda ortak bir nokta buldu.`, ex2:`Despite their differences, they found common ground.`, exTr2:`Farklılıklarına rağmen ortak bir zemin buldular.`, coll:`FIND common ground · common ground WITH/BETWEEN · seek common ground`},
  {en:`break even`, tr:`başa baş noktasına gelmek`, type:`kalıp`, uk:``, us:``, note:`"even" burada "eşit, denk" demektir: gelir ile gider birbirine eşitlenir.`, detail:`Gelirin gidere tam denk gelmesi; ne kâr ne zarar.`, ex:`The café took a year to break even.`, exTr:`Kafenin başa baş noktasına gelmesi bir yıl sürdü.`, ex2:`We hope to break even by next quarter.`, exTr2:`Gelecek çeyrekte başa baş noktasına gelmeyi umuyoruz.`, coll:`break even (ON sth) · TAKE a year to break even · break even BY (a date)`},
  {en:`backward compatible`, tr:`geriye dönük uyumlu (eski sürümlerle çalışan)`, type:`kalıp`, uk:``, us:``, note:`Teknoloji terimidir; yeni bir sürümün eski sürümlerle çalışabilmesini anlatır.`, detail:`Yeni bir sistemin ya da cihazın, eski sürümlerle sorunsuz çalışabilmesi.`, ex:`The new console is backward compatible with old games.`, exTr:`Yeni konsol, eski oyunlarla geriye dönük uyumludur.`, ex2:`Make sure the update is backward compatible.`, exTr2:`Güncellemenin geriye dönük uyumlu olduğundan emin ol.`, coll:`backward compatible WITH (old games/versions) · make sth backward compatible`},
  {en:`blend in`, tr:`ortama karışmak, göze batmamak`, type:`phrasal fiil`, uk:``, us:``, note:`"blend" (karışmak, harmanlanmak) + "in". Çevresine karışıp fark edilmemeyi anlatır.`, detail:`Etrafına uyum sağlayıp dikkat çekmemek.`, ex:`He wore grey to blend in with the crowd.`, exTr:`Kalabalığa karışıp göze batmamak için gri giydi.`, ex2:`Chameleons blend in with their surroundings.`, exTr2:`Bukalemunlar çevrelerine karışır.`, opposite:`stand out.`, coll:`blend in WITH (the crowd/surroundings) · wear sth TO blend in (karşıtı stand out)`},
  {en:`stir`, tr:`karıştırmak; kıpırdamak; (duygu) uyandırmak`, type:`kelime`, uk:`/stɜː/`, us:`/stɜːr/`, note:`Eski İngilizce "styrian" (hareket ettirmek) fiilinden.`, detail:`Kaşıkla karıştırmak; hafifçe kıpırdamak; ya da bir duyguyu harekete geçirmek.`, ex:`Her speech stirred the crowd.`, exTr:`Konuşması kalabalığı coşturdu.`, ex2:`Stir the soup so it doesn't stick.`, exTr2:`Çorbayı dibi tutmasın diye karıştır.`, coll:`stir the soup/mixture · stir the crowd · not stir (kıpırdamamak)`},
  {en:`pacemaker`, tr:`kalp pili; tempo belirleyici`, type:`kelime`, uk:`/ˈpeɪsmeɪkə/`, us:`/ˈpeɪsmeɪkər/`, note:`"pace" (tempo) + "maker" (yapan). Tıbbi anlamı 20. yüzyıl başında çıktı.`, detail:`Kalp atışını düzenleyen cihaz; ayrıca yarışta tempoyu belirleyen koşucu.`, ex:`A pacemaker keeps his heart beating steadily.`, exTr:`Kalp pili, kalbinin düzenli atmasını sağlıyor.`, ex2:`Doctors fitted him with a pacemaker last year.`, exTr2:`Doktorlar geçen yıl ona kalp pili taktı.`, coll:`FIT/FIT sb WITH a pacemaker · a pacemaker keeps the heart beating · HAVE a pacemaker`},
  {en:`Heimlich maneuver`, tr:`Heimlich manevrası`, type:`kalıp`, uk:`/ˈhaɪmlɪk məˈnuːvə/`, us:`/ˈhaɪmlɪk məˈnuːvər/`, note:`Tekniği 1974'te tarif eden Dr. Henry Heimlich'in adını taşır.`, detail:`Boğazına bir şey kaçan kişinin hava yolunu açmak için karnına yapılan itme hareketi.`, ex:`She performed the Heimlich maneuver and dislodged the food.`, exTr:`Heimlich manevrasını uygulayıp boğaza kaçan yemeği çıkardı.`, ex2:`Every lifeguard is trained in the Heimlich maneuver.`, exTr2:`Her cankurtaran Heimlich manevrası konusunda eğitimlidir.`, coll:`PERFORM/DO the Heimlich maneuver · be trained IN the Heimlich maneuver`},
  {en:`charley horse`, tr:`(bacakta) kas krampı`, type:`kalıp`, uk:`/ˈtʃɑːli hɔːs/`, us:`/ˈtʃɑːrli hɔːrs/`, note:`ABD beysbol argosundan gelen 19. yüzyıl deyimidir; kökeni tam olarak bilinmez.`, detail:`Genellikle bacakta olan, ani ve ağrılı kas krampı.`, ex:`I woke up with a charley horse in my calf.`, exTr:`Baldırımda bir kas krampıyla uyandım.`, ex2:`Stretching before bed helps prevent a charley horse.`, exTr2:`Yatmadan önce esnemek, kas krampını önlemeye yardımcı olur.`, coll:`GET/HAVE a charley horse · WAKE UP WITH a charley horse · a charley horse IN one's calf`},
  {en:`suck out`, tr:`emerek çekmek / çıkarmak`, type:`phrasal fiil`, uk:``, us:``, note:`"suck" (emmek) + "out". Sıvı ya da havanın vakumla çekilmesini anlatır.`, detail:`Bir sıvıyı ya da havayı emme yoluyla dışarı çekmek.`, ex:`The machine sucks out the excess moisture.`, exTr:`Makine, fazla nemi emerek dışarı çeker.`, ex2:`The dentist sucked out the saliva with a small tube.`, exTr2:`Diş hekimi tükürüğü küçük bir hortumla emerek çekti.`, coll:`suck OUT (moisture/air/saliva) · suck sth out WITH (a tube)`},
  {en:`casualties`, tr:`zayiat, kayıplar (ölü/yaralı)`, type:`kelime`, uk:`/ˈkæʒuəltiz/`, us:`/ˈkæʒuəltiz/`, note:`Latince "casus" (rastlantı, düşüş) kökünden.`, detail:`Savaşta ya da kazada ölen veya yaralanan kişiler.`, ex:`The earthquake caused heavy casualties.`, exTr:`Deprem ağır kayıplara yol açtı.`, ex2:`Fortunately, there were no casualties in the fire.`, exTr2:`Neyse ki yangında can kaybı olmadı.`, coll:`HEAVY/CIVILIAN casualties · CAUSE/SUFFER casualties · no casualties`},
  {en:`death toll`, tr:`ölü sayısı, can kaybı`, type:`kalıp`, uk:`/ˈdeθ təʊl/`, us:`/ˈdeθ toʊl/`, note:`"toll" burada "bedel, alınan sayı" demektir; bir olayın aldığı canların sayısını anlatır.`, detail:`Bir olayda hayatını kaybeden kişilerin toplam sayısı.`, ex:`The death toll from the flood rose to fifty.`, exTr:`Selde ölü sayısı elliye yükseldi.`, ex2:`Officials fear the death toll will rise.`, exTr2:`Yetkililer, ölü sayısının artmasından korkuyor.`, coll:`the death toll ROSE/RISES TO (a number) · the death toll FROM sth · a rising death toll`},
  {en:`indiscriminate`, tr:`ayrım gözetmeyen, gelişigüzel`, type:`sıfat`, uk:`/ˌɪndɪˈskrɪmɪnət/`, us:`/ˌɪndɪˈskrɪmɪnət/`, note:`"in-" (olumsuzluk) + "discriminate" (ayırt etmek, Latince "discriminare").`, detail:`Dikkatli bir seçim yapmadan, herkesi ya da her şeyi hedef alan.`, ex:`Indiscriminate bombing hit civilian areas.`, exTr:`Ayrım gözetmeyen bombardıman sivil bölgeleri vurdu.`, ex2:`The virus is indiscriminate; it infects everyone.`, exTr2:`Virüs ayrım gözetmez, herkese bulaşır.`, similar:`random, haphazard, wholesale. Fark: indiscriminate ayrım gözetmeden herkese ya da her şeye zarar verir; random rastgeledir; haphazard plansızdır.`, opposite:`selective, targeted, discriminating.`, coll:`indiscriminate bombing/killing/use · indiscriminate IN (its targets)`},
  {en:`crippled`, tr:`felç olmuş, işlemez hale gelmiş`, type:`sıfat`, uk:`/ˈkrɪpld/`, us:`/ˈkrɪpld/`, note:`Eski İngilizce "crypel" sözcüğünden.`, detail:`Ağır hasar görmüş, işleyemez hale gelmiş.`, ex:`The strike crippled the country's ports.`, exTr:`Grev, ülkenin limanlarını felç etti.`, ex2:`The war crippled the nation's economy.`, exTr2:`Savaş, ülkenin ekonomisini felç etti.`, extra:`İnsanlar için kullanımı bugün incitici sayılır; "disabled" tercih edilir. Sistem ya da ekonomi için mecazi kullanımı nötrdür.`, similar:`paralysed, incapacitated, disabled. Fark: (mecazi) crippled işlemez hale gelmedir; paralysed felçtir; incapacitated iş göremez kılınmadır. İnsanlar için "disabled" tercih edilir.`, opposite:`(mecazi) functioning, thriving.`, coll:`crippled BY (debt/strikes) · crippled the economy/ports · be left crippled`},
  {en:`arsonist`, tr:`kundakçı`, type:`kelime`, uk:`/ˈɑːsənɪst/`, us:`/ˈɑːrsənɪst/`, note:`Latince "ardere / arson-" (yanmak) kökünden.`, detail:`Kasten yangın çıkaran kişi.`, ex:`An arsonist set the warehouse ablaze.`, exTr:`Bir kundakçı depoyu ateşe verdi.`, ex2:`Police are hunting the arsonist responsible.`, exTr2:`Polis, sorumlu kundakçıyı arıyor.`, coll:`a suspected arsonist · HUNT/CATCH the arsonist · an arsonist SET sth ablaze`},
  {en:`cancel culture`, tr:`boykot / dışlama kültürü`, type:`kalıp`, uk:``, us:``, note:`Sosyal medya çağında ortaya çıkan bir terimdir: "cancel" burada birine desteği tamamen çekmek demektir.`, detail:`Bir kişiyi, kırıcı bulunan söz ya da davranışları nedeniyle toplu biçimde dışlama, desteği kesme pratiği.`, ex:`Critics say cancel culture stifles debate.`, exTr:`Eleştirmenler, dışlama kültürünün tartışmayı boğduğunu söyler.`, ex2:`The debate over cancel culture divides opinion.`, exTr2:`Dışlama kültürü tartışması, görüşleri ikiye bölüyor.`, coll:`the debate OVER cancel culture · cancel culture stifles/silences · a victim of cancel culture`},
  {en:`the cost of living continued to soar`, tr:`hayat pahalılığı fırlamaya devam etti`, type:`cümle`, uk:``, us:``, note:`Anahtar sözcük "soar": hızla, çok yükseğe çıkmak. "cost of living" ise geçim maliyeti, hayat pahalılığıdır.`, detail:`Yaşam masraflarının hızla ve durmadan yükselmesini anlatan bir kalıp.`, ex:`The cost of living continued to soar throughout the year.`, exTr:`Hayat pahalılığı yıl boyunca fırlamaya devam etti.`, ex2:`As the cost of living continued to soar, families cut back.`, exTr2:`Hayat pahalılığı fırlamaya devam ederken aileler harcamalarını kıstı.`, coll:`the cost of living continued to soar · AS the cost of living soared, ...`},
  {en:`come across`, tr:`rastlamak; (izlenim) bırakmak`, type:`phrasal fiil`, uk:``, us:``, note:`İki temel anlamı vardır: tesadüfen bulmak ve belli bir izlenim vermek.`, detail:`Bir şeye tesadüfen rastlamak; ya da karşıdakinde belli bir izlenim uyandırmak.`, ex:`I came across an old letter in the attic.`, exTr:`Tavan arasında eski bir mektuba rastladım.`, ex2:`He comes across as shy, but he isn't.`, exTr2:`Utangaç gibi görünüyor, ama değil.`, similar:`stumble upon, encounter; seem, appear. Fark: come across tesadüfen bulmak ya da bir izlenim vermektir; stumble upon şans eseri bulmaktır; encounter karşılaşmaktır.`, coll:`come ACROSS sth (rastlamak) · come across AS (shy) (izlenim vermek)`},
  {en:`put off`, tr:`ertelemek; soğutmak, isteğini kaçırmak`, type:`phrasal fiil`, uk:``, us:``, note:`İki ayrı anlamı vardır: bir işi ileri atmak, ya da birini bir şeyden tiksindirip vazgeçirmek.`, detail:`Bir şeyi sonraya bırakmak; ya da birinin ilgisini, iştahını kaçırmak.`, ex:`They put off the meeting until Friday.`, exTr:`Toplantıyı cumaya ertelediler.`, ex2:`The smell put me off my food.`, exTr2:`Koku iştahımı kaçırdı.`, similar:`postpone, delay, defer; deter, discourage. Fark: put off ertelemek ya da birinin isteğini kaçırmaktır; postpone ve defer resmi ertelemedir; deter caydırır.`, opposite:`bring forward, expedite; (çekim) attract, appeal.`, coll:`put OFF (a meeting) UNTIL · put sb off (sth) · be put off BY sth`},
  {en:`wind up`, tr:`sonunda (bir durumda) bulmak kendini; bitirmek`, type:`phrasal fiil`, uk:`/waɪnd ʌp/`, us:`/waɪnd ʌp/`, note:`Okunuşu /waɪnd/ (saati kurmak) gibidir.`, detail:`Sonunda beklenmedik bir durumda bulmak kendini; bir şeyi bitirmek; (İng.) takılıp sinirlendirmek.`, ex:`We wound up lost in the old town.`, exTr:`Sonunda kendimizi eski şehirde kaybolmuş halde bulduk.`, ex2:`Stop winding your brother up!`, exTr2:`Kardeşini kızdırmayı bırak!`, extra:`İngiliz İngilizcesinde ayrıca "birini takılarak kızdırmak" anlamı taşır.`, coll:`wind up (lost/in a situation) · wind sb up (kızdırmak) · wind up doing sth`},
  {en:`fall back on`, tr:`sıkışınca başvurmak, güvence olarak dayanmak`, type:`phrasal fiil`, uk:``, us:``, note:`"geriye düşüp bir şeyin üstüne yaslanmak" imgesini taşır: bir güvence, yedek plan.`, detail:`Diğer planlar tutmadığında güvenebileceğin bir şeye başvurmak.`, ex:`If the business fails, she can fall back on teaching.`, exTr:`İş batarsa öğretmenliğe geri dönüp ona tutunabilir.`, ex2:`It's good to have savings to fall back on.`, exTr2:`İhtiyaç anında başvurabileceğin bir birikimin olması iyidir.`, coll:`fall back ON sth (teaching/savings) · have sth to fall back on`},
  {en:`get around to`, tr:`(nihayet) fırsat bulup yapmak`, type:`phrasal fiil`, uk:``, us:``, note:`Sürekli ertelenen bir işe sonunda sıra gelmesini anlatır.`, detail:`Ertelediğin bir şeyi nihayet yapacak vakti ya da fırsatı bulmak.`, ex:`I never got around to fixing the fence.`, exTr:`Çiti tamir etmeye bir türlü sıra gelmedi.`, ex2:`I'll get around to it this weekend.`, exTr2:`Bu hafta sonu sıra gelince yaparım.`, coll:`get around TO (doing) sth · never get around to it · finally get around to sth`},
  {en:`figure out`, tr:`çözmek, anlamak`, type:`phrasal fiil`, uk:``, us:``, note:`"figure" burada "hesaplamak, akıl yürütmek" anlamındadır.`, detail:`Bir şeyi düşünüp çözmek ya da anlamak.`, ex:`I can't figure out how this works.`, exTr:`Bunun nasıl çalıştığını bir türlü çözemiyorum.`, ex2:`We need to figure out what went wrong.`, exTr2:`Neyin ters gittiğini çözmemiz gerek.`, similar:`work out, solve, make sense of. Fark: hepsi çözmek ya da anlamaktır; figure out ve work out günlük dildir; solve daha resmidir.`, coll:`figure OUT how/what/why · figure out a problem · can't figure sth out`},
  {en:`point out`, tr:`dikkat çekmek, belirtmek`, type:`phrasal fiil`, uk:``, us:``, note:`Birebir "parmakla göstermek"; bir gerçeğe dikkat çekmeyi anlatır.`, detail:`Bir olguya dikkat çekmek, işaret etmek.`, ex:`She pointed out a mistake in my essay.`, exTr:`Denememdeki bir hataya dikkat çekti.`, ex2:`It's worth pointing out the risks.`, exTr2:`Riskleri belirtmekte fayda var.`, coll:`point OUT (a mistake) · point out THAT ... · it's worth pointing out`},
  {en:`bring up`, tr:`(konu) açmak; (çocuk) yetiştirmek`, type:`phrasal fiil`, uk:``, us:``, note:`İki temel anlamı vardır: bir konuyu gündeme getirmek ve bir çocuğu büyütmek.`, detail:`Bir konuyu söz konusu etmek; ya da bir çocuğu büyütüp yetiştirmek.`, ex:`Don't bring up politics at dinner.`, exTr:`Yemekte siyaset konusunu açma.`, ex2:`She was brought up by her grandparents.`, exTr2:`Onu, dedesiyle büyükannesi büyüttü.`, similar:`raise, mention; rear. Fark: bring up ya konu açmaktır ya da çocuk büyütmektir; raise ikisini de karşılar; mention yalnızca anmaktır; rear çocuk ya da hayvan yetiştirmektir.`, coll:`bring UP (a topic/politics) · be brought up BY (grandparents) · bring up a child`},
  {en:`turn out`, tr:`(sonunda) öyle çıkmak, olmak`, type:`phrasal fiil`, uk:``, us:``, note:`Bir şeyin sonunda nasıl sonuçlandığını ya da aslında öyle olduğunu anlatır.`, detail:`Sonunda belli bir şekilde gelişmek ya da öyle olduğu anlaşılmak.`, ex:`Everything turned out fine.`, exTr:`Sonunda her şey yoluna girdi.`, ex2:`It turned out that he was right all along.`, exTr2:`Baştan beri haklı olduğu ortaya çıktı.`, similar:`end up, transpire, prove to be. Fark: turn out sonunda öyle çıkmaktır; end up bir durumda son bulmaktır; transpire resmi dilde ortaya çıkmaktır.`, coll:`turn out (fine/well) · it turned out THAT ... · turn out TO BE sth`},
  {en:`carry out`, tr:`yürütmek, gerçekleştirmek, yerine getirmek`, type:`phrasal fiil`, uk:``, us:``, note:`Bir görevi ya da planı fiilen uygulamayı anlatır.`, detail:`Bir görevi ya da işi yerine getirmek, tamamlamak.`, ex:`Scientists carried out several tests.`, exTr:`Bilim insanları birkaç test gerçekleştirdi.`, ex2:`The soldiers carried out their orders.`, exTr2:`Askerler emirleri yerine getirdi.`, coll:`carry OUT (tests/orders/a plan) · carry out research/an attack`},
  {en:`back up`, tr:`desteklemek; yedeklemek; geri gitmek`, type:`phrasal fiil`, uk:``, us:``, note:`Üç anlamı yaygındır: destek olmak, kopya almak ve geri geri gitmek.`, detail:`Birini ya da bir iddiayı desteklemek; veriyi yedeklemek; aracı geri sürmek.`, ex:`Can you back up your claim with data?`, exTr:`İddianı verilerle destekleyebilir misin?`, ex2:`Always back up your files before an update.`, exTr2:`Güncellemeden önce dosyalarını her zaman yedekle.`, coll:`back UP (a claim) WITH (data) · back up your files · back sb up`},
  {en:`narrow down`, tr:`(seçenekleri) daraltmak`, type:`phrasal fiil`, uk:``, us:``, note:`"narrow" (dar) + "down". Geniş bir listeyi azaltmayı anlatır.`, detail:`Seçenek ya da olasılıkların sayısını azaltmak.`, ex:`We narrowed down the list to three names.`, exTr:`Listeyi üç isme kadar daralttık.`, ex2:`Can you narrow it down to a single cause?`, exTr2:`Bunu tek bir sebebe indirebilir misin?`, similar:`whittle down, reduce. Fark: narrow down seçenekleri daraltır; whittle down azalta azalta indirir; reduce geneldir.`, opposite:`broaden, widen.`, coll:`narrow DOWN (the list) TO (three) · narrow it down to a single cause`},
  {en:`the elephant in the room`, tr:`herkesin gördüğü ama konuşulmayan sorun`, type:`deyim`, uk:``, us:``, note:`Odadaki bir fil kadar apaçık, ama kimsenin dile getirmediği bir mesele imgesi.`, detail:`Ortada bariz duran ama kimsenin konuşmak istemediği rahatsız edici sorun.`, ex:`Let's address the elephant in the room: the budget.`, exTr:`Şu herkesin bildiği ama kimsenin açmadığı konuya girelim: bütçe.`, ex2:`Nobody mentioned the elephant in the room: he was leaving.`, exTr2:`Kimse ortadaki o bariz gerçeği dile getirmedi: gidiyordu.`, coll:`ADDRESS/IGNORE the elephant in the room · the elephant in the room IS ...`},
  {en:`cut corners`, tr:`işi baştan savmak, kestirmeden yapmak`, type:`deyim`, uk:``, us:``, note:`Birebir "köşeleri kesmek"; yolun köşelerini keserek kısa yoldan, ama özensizce gitmek.`, detail:`Bir işi ucuza ya da hızlıca yapmak için gerekli adımları atlamak.`, ex:`They cut corners on safety to save money.`, exTr:`Para kısmak için güvenlikten ödün verip işi baştan savdılar.`, ex2:`You can't cut corners when it comes to health.`, exTr2:`İş sağlığa gelince baştan savma yapılmaz.`, similar:`take shortcuts, skimp. Fark: cut corners kalite ya da kuraldan ödün vererek kestirmeden gitmektir; take shortcuts nötr olabilir; skimp cimrilik ederek eksik yapmaktır.`, coll:`cut corners ON (safety/quality) · can't cut corners WHEN it comes to sth`},
  {en:`on the fence`, tr:`kararsız, arada kalmış`, type:`deyim`, uk:``, us:``, note:`İki tarafın ortasındaki çitin üstünde oturup hangi tarafa ineceğine karar verememe imgesi.`, detail:`İki seçenek arasında bir türlü karar verememek.`, ex:`I'm still on the fence about the job offer.`, exTr:`İş teklifi konusunda hâlâ kararsızım.`, ex2:`Voters are still on the fence.`, exTr2:`Seçmenler hâlâ kararsız.`, similar:`undecided, torn, in two minds. Fark: hepsi kararsızlıktır; on the fence taraf tutmamayı, torn iki istek arasında yırtılmayı, in two minds ikilemi vurgular.`, opposite:`decided, resolute.`, coll:`BE/SIT on the fence ABOUT sth · still on the fence`},
  {en:`a double-edged sword`, tr:`iki ucu keskin kılıç`, type:`deyim`, uk:``, us:``, note:`İki yüzü de kesen bir kılıç: hem işine yarar hem seni de keser.`, detail:`Hem olumlu hem olumsuz sonuçları olan bir şey.`, ex:`Fame is a double-edged sword.`, exTr:`Şöhret, iki ucu keskin bir kılıçtır.`, ex2:`Social media is a double-edged sword.`, exTr2:`Sosyal medya, iki ucu keskin bir kılıçtır.`, coll:`sth IS a double-edged sword · fame/technology is a double-edged sword`},
  {en:`hit the nail on the head`, tr:`tam üstüne basmak, taşı gediğine koymak`, type:`deyim`, uk:``, us:``, note:`Çiviyi tam kafasından vurmak: tam isabet ettirmek.`, detail:`Bir durumun asıl sebebini ya da özünü tam olarak isabetle söylemek.`, ex:`You hit the nail on the head with that comment.`, exTr:`O yorumunla tam üstüne bastın.`, ex2:`Her analysis hit the nail on the head.`, exTr2:`Analizi tam üstüne bastı.`, coll:`hit the nail on the head (WITH a comment) · you've hit the nail on the head`},
  {en:`the tip of the iceberg`, tr:`buzdağının görünen ucu`, type:`deyim`, uk:``, us:``, note:`Buzdağının yalnızca küçük bir kısmı su üstünde görünür; asıl büyük kısım altta gizlidir.`, detail:`Çok daha büyük bir sorunun yalnızca küçük, görünen parçası.`, ex:`These complaints are just the tip of the iceberg.`, exTr:`Bu şikâyetler, buzdağının yalnızca görünen ucu.`, ex2:`The scandal was only the tip of the iceberg.`, exTr2:`Skandal, buzdağının yalnızca görünen ucuydu.`, coll:`sth is (just/only) the tip of the iceberg · the tip of the iceberg`},
  {en:`play devil's advocate`, tr:`bilerek karşı tarafı savunmak`, type:`deyim`, uk:``, us:``, note:`Katolik Kilisesi'nde azizlik ilanına karşı argüman üretmekle görevli kişinin ("advocatus diaboli") rolünden gelir.`, detail:`Tartışmayı sınamak için, aslında katılmadığın karşı görüşü kasıtlı olarak savunmak.`, ex:`Let me play devil's advocate for a moment.`, exTr:`Bir an için bilerek karşı tarafı savunayım.`, ex2:`I don't disagree; I'm just playing devil's advocate.`, exTr2:`Karşı çıkmıyorum, sadece bilerek karşı tarafı savunuyorum.`, coll:`PLAY devil's advocate · just playing devil's advocate · let me play devil's advocate`},
  {en:`in the long run`, tr:`uzun vadede`, type:`deyim`, uk:``, us:``, note:`"run" burada bir zaman aralığını, gidişatı anlatır: uzun koşuda, uzun vadede.`, detail:`Uzun bir süre boyunca, nihayetinde.`, ex:`Eating well pays off in the long run.`, exTr:`İyi beslenmek uzun vadede karşılığını verir.`, ex2:`It may cost more now but saves money in the long run.`, exTr2:`Şimdi daha pahalı olabilir ama uzun vadede para kazandırır.`, similar:`in the end, ultimately, over time. Fark: in the long run uzun vadeyi; in the end nihai sonucu; ultimately en sonunda; over time zamanla anlamını verir.`, opposite:`in the short term.`, coll:`IN the long run · pay off/save money in the long run (karşıtı in the short term)`},
  {en:`take something with a grain of salt`, tr:`şüpheyle karşılamak, ihtiyatla yaklaşmak`, type:`deyim`, uk:``, us:``, note:`Latince "cum grano salis" deyiminden gelir: "bir tutam tuzla", yani körü körüne yutmadan.`, detail:`Bir bilgiye tam güvenmemek, temkinli yaklaşmak.`, ex:`Take online reviews with a grain of salt.`, exTr:`İnternetteki yorumları ihtiyatla karşıla.`, ex2:`He tends to exaggerate, so take his stories with a grain of salt.`, exTr2:`Abartma eğilimi var, o yüzden anlattıklarını ihtiyatla karşıla.`, coll:`take sth WITH a grain of salt · take (reviews/stories) with a grain of salt`},
  {en:`get the hang of`, tr:`(bir işin) püf noktasını kapmak, alışmak`, type:`deyim`, uk:``, us:``, note:`Bir işin "asılış, tutuş" biçimini kavramak imgesinden gelir.`, detail:`Bir şeyi biraz pratikle yapmayı öğrenmek, işin ustalığını kazanmak.`, ex:`It's tricky at first, but you'll get the hang of it.`, exTr:`Başta çetrefil, ama zamanla püf noktasını kaparsın.`, ex2:`Once you get the hang of cycling, you never forget.`, exTr2:`Bisiklete binmenin tekniğini bir kez kaptın mı, asla unutmazsın.`, coll:`get the hang OF sth · you'll get the hang of it · once you get the hang of it`},
  {en:`reckon`, tr:`sanmak, düşünmek; hesaplamak`, type:`kelime`, uk:`/ˈrekən/`, us:`/ˈrekən/`, note:`Eski İngilizce "gerecenian" (saymak, anlatmak) fiilinden.`, detail:`Bir şeyi düşünmek ya da tahmin etmek; ayrıca hesaplamak.`, ex:`I reckon it'll rain later.`, exTr:`Bence sonra yağmur yağar.`, ex2:`How much do you reckon it'll cost?`, exTr2:`Sence ne kadar tutar?`, extra:`Günlük İngiliz İngilizcesinde "bence, sanırım" yerine çok sık kullanılır.`, similar:`think, suppose, guess. Fark: reckon günlük ve İngiliz İngilizcesinde "bence" der; suppose bir çıkarımdır; guess tahmindir.`, coll:`I reckon (THAT) ... · how much do you reckon ...? · reckon sth to be sth`},
  {en:`subtle`, tr:`ince, sezilmesi güç, incelikli`, type:`sıfat`, uk:`/ˈsʌtl/`, us:`/ˈsʌtl/`, note:`Latince "subtilis" (ince, narin) sözcüğünden.`, detail:`Hemen fark edilmeyen, narin, zekice ayarlanmış.`, ex:`There was a subtle change in her tone.`, exTr:`Ses tonunda güç fark edilen bir değişim vardı.`, ex2:`The wine has subtle notes of cherry.`, exTr2:`Şarapta hafif, güç sezilen kiraz notaları var.`, extra:`Yazımdaki "b" harfi okunmaz.`, similar:`delicate, understated, nuanced. Fark: subtle fark edilmesi güç bir incelliktir; understated abartısız, gösterişsizdir; nuanced ince ayrımlar taşır.`, opposite:`obvious, blatant, overt.`, coll:`a subtle change/difference/hint · subtle notes OF sth · so subtle`},
  {en:`crucial`, tr:`çok önemli, kritik, hayati`, type:`sıfat`, uk:`/ˈkruːʃl/`, us:`/ˈkruːʃl/`, note:`Latince "crux / cruc-" (haç, yol ayrımı) kökünden: belirleyici bir kavşak.`, detail:`Son derece önemli, sonucu belirleyici.`, ex:`Timing is crucial in comedy.`, exTr:`Komedide zamanlama çok önemlidir.`, ex2:`The next few days are crucial for the patient.`, exTr2:`Önümüzdeki birkaç gün, hasta için hayati önemde.`, similar:`vital, essential, pivotal. Fark: crucial ve vital hayati derecede önemlidir; essential olmazsa olmazdır; pivotal her şeyin döndüğü belirleyici noktadır.`, opposite:`trivial, minor, negligible.`, coll:`crucial TO/FOR sth · crucial IN (doing) sth · play a crucial role · absolutely crucial`},
  {en:`considerable`, tr:`hatırı sayılır, epeyce`, type:`sıfat`, uk:`/kənˈsɪdərəbl/`, us:`/kənˈsɪdərəbl/`, note:`"consider" (göz önünde bulundurmak, Latince "considerare") fiilinden.`, detail:`Boyut, miktar ya da önem bakımından büyük, dikkate değer.`, ex:`The project took a considerable amount of time.`, exTr:`Proje hatırı sayılır bir zaman aldı.`, ex2:`She has considerable experience in the field.`, exTr2:`Alanında hatırı sayılır bir deneyime sahip.`, similar:`substantial, significant, sizeable. Fark: considerable ve substantial miktarca büyüktür; significant anlamca önemlidir; sizeable gözle görülür büyüklüktedir.`, opposite:`negligible, slight, trifling.`, coll:`a considerable amount/number OF sth · considerable experience/time/effort`},
  {en:`compelling`, tr:`ikna edici, sürükleyici`, type:`sıfat`, uk:`/kəmˈpelɪŋ/`, us:`/kəmˈpelɪŋ/`, note:`Latince "compellere" (zorlamak, sürüklemek) fiilinden: insanı adeta kabule zorlayan.`, detail:`Görmezden gelinemeyecek kadar inandırıcı ya da ilgi çekici.`, ex:`She made a compelling argument.`, exTr:`Çok ikna edici bir argüman sundu.`, ex2:`There is compelling evidence for the theory.`, exTr2:`Teoriyi destekleyen ikna edici kanıtlar var.`, similar:`convincing, persuasive, cogent. Fark: compelling karşı konulamaz derecede ilgi çeker ya da ikna eder; persuasive ikna etmeye çalışır; cogent mantıkça sağlamdır.`, opposite:`unconvincing, weak, feeble.`, coll:`MAKE a compelling argument/case · compelling evidence/reason · a compelling story`},
  {en:`deliberate`, tr:`kasıtlı, bilerek yapılan; ölçülü`, type:`sıfat`, uk:`/dɪˈlɪbərət/`, us:`/dɪˈlɪbərət/`, note:`Latince "deliberare" (tartıp değerlendirmek) fiilinden.`, detail:`Bilerek, kasten yapılan; ayrıca aceleye getirmeden, ölçülü.`, ex:`It was a deliberate attempt to mislead.`, exTr:`Bu, kasıtlı bir yanıltma girişimiydi.`, ex2:`He spoke in a slow, deliberate manner.`, exTr2:`Yavaş ve ölçülü bir tavırla konuştu.`, extra:`Sıfat hali /dɪˈlɪbərət/, fiil hali ise /dɪˈlɪbəreɪt/ olarak farklı okunur.`, similar:`intentional, calculated, premeditated. Fark: deliberate hem kasıtlı hem ölçülüdür; intentional yalnızca kasıtlıdır; calculated çıkar hesabıyladır; premeditated önceden tasarlanmıştır.`, opposite:`accidental, unintentional, impulsive.`, coll:`a deliberate attempt TO do sth · a slow, deliberate manner · deliberate act`},
  {en:`inevitable`, tr:`kaçınılmaz`, type:`sıfat`, uk:`/ɪnˈevɪtəbl/`, us:`/ɪnˈevɪtəbl/`, note:`Latince "inevitabilis" (kaçınılamaz); "e-vitare" (kaçınmak) kökünden.`, detail:`Olması kesin, önüne geçilemez.`, ex:`With such spending, debt was inevitable.`, exTr:`Bu kadar harcamayla borç kaçınılmazdı.`, ex2:`Change is inevitable.`, exTr2:`Değişim kaçınılmazdır.`, similar:`unavoidable, inescapable, certain. Fark: inevitable ve unavoidable kaçınılmazdır; inescapable kurtuluşu olmayandır; certain kesindir ama illa istenmeyen değildir.`, opposite:`avoidable, preventable.`, coll:`sth was/is inevitable · it was inevitable THAT ... · the inevitable outcome`},
  {en:`tendency`, tr:`eğilim, yatkınlık`, type:`kelime`, uk:`/ˈtendənsi/`, us:`/ˈtendənsi/`, note:`Latince "tendere" (uzanmak, yönelmek) kökünden.`, detail:`Belli bir biçimde davranma ya da gelişme meyli.`, ex:`He has a tendency to interrupt.`, exTr:`Sözü kesme eğilimi var.`, ex2:`Prices show an upward tendency.`, exTr2:`Fiyatlar yukarı yönlü bir eğilim gösteriyor.`, similar:`inclination, propensity, penchant. Fark: tendency genel bir eğilimdir; inclination kişisel meyildir; propensity çoğu olumsuz, güçlü bir eğilimdir; penchant hoşlanılan bir düşkünlüktür.`, opposite:`aversion, disinclination.`, coll:`HAVE a tendency TO do sth · a tendency TOWARDS sth · a natural/upward tendency`},
  {en:`not bat an eyelid`, tr:`istifini bozmamak, gözünü kırpmamak`, type:`deyim`, uk:``, us:``, note:`"bat" burada gözü kırpmak/oynatmak demektir; birebir "gözünü bile kırpmamak".`, detail:`Şaşırtıcı, sarsıcı ya da olağandışı bir şey karşısında hiç tepki vermemek, hiç etkilenmemiş görünmek.`, ex:`She didn't bat an eyelid when he told her the price.`, exTr:`Fiyatı söylediğinde gözünü bile kırpmadı.`, ex2:`He handed over a fortune without batting an eyelid.`, exTr2:`Bir servet öderken gözünü bile kırpmadı.`, coll:`not bat an eyelid (WHEN/AT sth) · WITHOUT batting an eyelid`},
  {en:`by all accounts`, tr:`herkesin dediğine göre, anlaşılan`, type:`kalıp`, uk:``, us:``, note:`Buradaki "account" "anlatı, ifade" demektir; yani "bütün anlatılara göre".`, detail:`Duyulan, okunan tüm kaynaklara ve genel kanıya göre; söylenenlere bakılırsa.`, ex:`By all accounts, the party was a huge success.`, exTr:`Herkesin dediğine göre parti büyük bir başarıydı.`, ex2:`By all accounts, she is an excellent teacher.`, exTr2:`Anlaşılan, o mükemmel bir öğretmen.`, coll:`BY all accounts, ... (cümle başında) · by all accounts a success`}
];

/* ============ KURULUM ============ */
WORDS.forEach((w,i)=>{ w._i = i; });

// kelime arama tablosu: her İngilizce biçim -> kelime kaydı
const LOOKUP = {};
WORDS.forEach(w=>{ w.en.split('/').map(x=>x.trim()).filter(Boolean).forEach(f=>{ LOOKUP[f.toLowerCase()] = w; }); });

const ARTICLES = [
{ title:`The Takeover`,
  en:`Nadia ran the company with a {{ruthless}} focus on profit. She was {{blunt}} in every meeting: "Cut costs or leave." Last year a single {{blunder}} nearly sank the firm, so now she held every manager {{accountable}}.

Then a scandal broke. A rival claimed the last contract was {{rigged}}, won through bribes and {{fake claims}}. Nadia said the numbers were clean, but the two reports kept {{contradicting}} each other. The board was {{on the fence}}: some wanted her gone, others said she had the {{moral fibre and merits}} to survive.

"We can't ignore {{the elephant in the room}}," a director said. "If we {{cut corners}} on safety, someone gets hurt." Nadia refused to {{hoodwink}} anyone. "We barely {{break even}} as it is," she snapped. "Hiding a fault would make me a {{hypocrite}}. So we tell the truth and {{deal with it}}."`,
  tr:`Nadia şirketi kâra acımasız bir odakla yönetiyordu. Her toplantıda dobraydı: "Ya masrafları kısın ya da gidin." Geçen yıl tek bir gaf firmayı neredeyse batırmıştı, bu yüzden artık her yöneticiyi sorumlu tutuyordu.

Derken bir skandal patladı. Bir rakip, son ihalenin hileli olduğunu, rüşvet ve sahte iddialarla kazanıldığını öne sürdü. Nadia rakamların temiz olduğunu söyledi ama iki rapor sürekli birbiriyle çelişiyordu. Yönetim kurulu kararsızdı: kimisi onun gitmesini istiyor, kimisi ayakta kalacak ahlaki değerler ve erdemlere sahip olduğunu söylüyordu.

"Şu herkesin gördüğü ama konuşmadığı sorunu görmezden gelemeyiz," dedi bir üye. "Güvenlikte işi baştan savarsak biri zarar görür." Nadia kimseyi kandırmaya yanaşmadı. "Zaten zar zor başa baş noktasındayız," diye çıkıştı. "Bir kusuru gizlemek beni ikiyüzlü yapar. O yüzden gerçeği söyler ve idare ederiz."`
},
{ title:`The Fire on Elm Street`,
  en:`The blaze started just after midnight. {{By all accounts|by all accounts}} it was no accident: an {{arsonist}} had poured fuel down the stairwell, and the flames spread in an {{indiscriminate}} rush, sparing nothing.

Neighbours fled to the {{curbside}} in an {{eerie}} silence. An old, damp {{bunker}} from the war filled with families. Firefighters worked to {{suck out}} the smoke and {{stir}} the trapped air.

By dawn the {{death toll}} stood at four, with dozens more among the {{casualties}}. The fire had {{crippled}} half the district; shops that were already {{stagnant}} would never reopen. As {{the cost of living continued to soar}}, few could rebuild. Police suspected a {{clandestine}} feud. It seemed almost {{cruel}} that one match could undo so many lives.`,
  tr:`Yangın gece yarısını biraz geçe başladı. Herkesin dediğine göre kaza değildi: bir kundakçı merdiven boşluğuna yakıt dökmüştü ve alevler ayrım gözetmeyen bir hızla yayıldı, hiçbir şeyi esirgemedi.

Komşular tekinsiz bir sessizlik içinde yol kenarına kaçtı. Savaştan kalma nemli, eski bir sığınak ailelerle doldu. İtfaiyeciler dumanı emerek çekmeye ve sıkışan havayı karıştırmaya çalıştı.

Şafakta ölü sayısı dörde ulaştı, onlarca kişi de yaralılar arasındaydı. Yangın ilçenin yarısını felç etmişti; zaten durgun olan dükkânlar bir daha açılmayacaktı. Hayat pahalılığı fırlamaya devam ederken çok azı yeniden inşa edebildi. Polis gizli bir husumetten şüphelendi. Tek bir kibritin bunca hayatı yıkması neredeyse zalimceydi.`
},
{ title:`Mara and the Clip`,
  en:`The show followed the {{tangled love lives}} of five roommates, and the public loved it. Its star, Mara, adored the {{limelight}} but rarely agreed to {{share the limelight}} with the cast.

When an old clip surfaced, {{cancel culture}} came for her overnight. Fans were {{exasperated}}; one co-star grew {{agitated}}, another {{perturbed}}. On camera Mara did not {{bat an eyelid|not bat an eyelid}}, though inside she was afraid. Her friends spent nights {{commiserating}} with her.

Instead of trying to {{get someone back|get someone back for something}} or {{start a vendetta against}} her critics, she {{came across|come across}} as humble. A {{greedy}} agent urged a lawsuit, but attacking a teenager online would be {{way below the belt}}. "I should {{take a leaf out of|take a leaf out of someone's book}} my grandmother," she said. In the end the two sides found {{common ground}}, and a quiet {{indulgence}} replaced the noise. Mara slowly learned to {{blend in}} again.`,
  tr:`Dizi, beş ev arkadaşının karmakarışık aşk hayatlarını anlatıyordu ve halk buna bayılıyordu. Yıldızı Mara ilgi odağı olmaya bayılırdı ama parlayan anı oyuncularla paylaşmaya pek yanaşmazdı.

Eski bir video ortaya çıkınca dışlama kültürü bir gecede peşine düştü. Hayranlar bezmişti; bir oyuncu arkadaşı telaşlandı, bir diğeri huzursuz oldu. Mara kamera önünde gözünü bile kırpmadı, içten içe korksa da. Arkadaşları geceleri onunla dertleşerek geçirdi.

Eleştirenlerden acısını çıkarmaya ya da onlara karşı husumet başlatmaya çalışmak yerine alçakgönüllü göründü. Açgözlü bir menajer dava açmaya itti ama internette bir gence saldırmak çok ayıp olurdu. "Büyükannemi örnek almalıyım," dedi. Sonunda iki taraf ortak bir zemin buldu; gürültünün yerini sakin bir keyif aldı. Mara yavaş yavaş yeniden ortama karışmayı öğrendi.`
},
{ title:`Dinner Scare`,
  en:`At the family dinner, Grandpa suddenly went pale and could not breathe. A fish bone had lodged in his throat. Aunt Lena, a nurse, rushed over and performed the {{Heimlich maneuver|heimlich maneuver}}, thrusting hard until the bone shot out.

Grandpa's {{pacemaker}} kept his heart steady through the shock. Once he could speak, he gave a weak {{nod}}. His {{eyelids|eyelid}} were heavy, and a loud {{hiccough}} made everyone laugh with relief.

"That was no small thing," Mum said, cutting the rest of the fish along a clean {{slit}}. Earlier that day Grandpa had pulled a muscle, a painful {{charley horse}}, and joked that old age was a {{burden}}. But moments like this reminded us how {{valuable}}, even {{irreplaceable}}, his presence was. In the tank nearby, a goldfish opened its {{gills|gill}}, calm as ever.`,
  tr:`Aile yemeğinde dede birden bembeyaz oldu ve nefes alamadı. Boğazına bir kılçık takılmıştı. Hemşire olan Lena teyze koşup Heimlich manevrasını uyguladı; kılçık fırlayana dek sert sert bastırdı.

Dedenin kalp pili, şok boyunca kalbini düzenli tuttu. Konuşabilince hafifçe başını salladı. Göz kapakları ağırlaşmıştı ve yüksek bir hıçkırık herkesi rahatlamayla güldürdü.

"Az buz iş değildi," dedi annem, kalan balığı düzgün bir yarık boyunca keserken. O gün erken saatte dede bir kasını incitmiş, acı veren bir kramp yaşamış ve yaşlılığın bir yük olduğuna şaka yapmıştı. Ama böyle anlar bize onun varlığının ne kadar değerli, hatta yeri doldurulamaz olduğunu hatırlattı. Yanındaki akvaryumda bir japon balığı, her zamanki kadar sakin, solungaçlarını açıp kapadı.`
},
{ title:`Launch Week`,
  en:`Our team had a week to {{carry out}} the new launch, and nobody could {{figure out}} where to start. After a short {{preamble}}, the manager began to {{narrow down}} the tasks. The new system also had to stay {{backward compatible}} with the old one.

"Let me {{point out}} one risk," said Omar. "If the server fails, what do we {{fall back on}}?" Someone had forgotten to {{back up}} the files, a job we kept meaning to {{get around to}}. We could not {{put off}} the launch again.

I had {{come across}} a similar plan online and, {{by all accounts|by all accounts}}, it had {{turned out|turn out}} well. "Before we decide, let's {{think it through}}," Omar said. "I {{reckon}} we can recover our costs in a month." It took a while to {{get the hang of}} the tools, but if we {{bring up}} problems early, the project might not {{wind up}} a disaster.`,
  tr:`Ekibimizin yeni lansmanı gerçekleştirmek için bir haftası vardı ve kimse nereden başlayacağını çözemiyordu. Kısa bir girişin ardından yönetici görevleri daraltmaya başladı. Yeni sistemin ayrıca eskisiyle geriye dönük uyumlu kalması gerekiyordu.

"Bir riske dikkat çekeyim," dedi Omar. "Sunucu çökerse neye başvuracağız?" Biri dosyaları yedeklemeyi unutmuştu; sürekli "sıra gelince yaparız" dediğimiz bir işti. Lansmanı yine erteleyemezdik.

İnternette benzer bir plana rastlamıştım ve herkesin dediğine göre iyi sonuç vermişti. "Karar vermeden önce iyice düşünelim," dedi Omar. "Bence bir ayda masrafımızı çıkarırız." Araçların tekniğini kapmak biraz sürdü ama sorunları erken açarsak proje bir felakete dönüşmeyebilir.`
},
{ title:`On Advice and Fame`,
  en:`Good advice is often {{subtle}}, and its worth only shows {{in the long run}}. A single tip can be {{crucial}}, yet we ignore what is quietly {{considerable}} and chase what is loud.

Fame is {{a double-edged sword}}: it opens doors but invites judgement. When a critic said success is mostly luck, he {{hit the nail on the head}}, though that was only {{the tip of the iceberg}}. Treat bold promises with care; {{take them with a grain of salt|take something with a grain of salt}}. A {{compelling}} argument can still be false. It helps to {{play devil's advocate}} and raise the opposite view in a {{deliberate}} test of your own idea.

Ambition has a {{tendency}} to blind us, so burnout feels almost {{inevitable}} and is {{detrimental}} to work and health. In a quiet {{detached house}} far from the city, a novelist known only by her {{pen name}} understood this. Her {{absence}} from the spotlight was chosen on purpose. "A star envies a newer star. {{How is that news|how is that news}}?" she wrote.`,
  tr:`İyi tavsiye çoğu zaman inceliklidir ve değeri ancak uzun vadede belli olur. Tek bir öneri hayati olabilir; oysa sessizce hatırı sayılır olanı görmezden gelip gürültülü olanın peşine düşeriz.

Şöhret iki ucu keskin bir kılıçtır: kapılar açar ama yargılanmayı davet eder. Bir eleştirmen başarının çoğunlukla şans olduğunu söylediğinde tam üstüne bastı, ama bu buzdağının yalnızca görünen ucuydu. İddialı vaatlere temkinli yaklaş; onları şüpheyle karşıla. İkna edici bir argüman bile yanlış olabilir. Kendi fikrini sınamak için bilerek karşı tarafı savunmak ve zıt görüşü ortaya atmak işe yarar.

Hırsın gözümüzü karartma eğilimi vardır; bu yüzden tükenmişlik neredeyse kaçınılmazdır ve hem işe hem sağlığa zararlıdır. Şehirden uzak, sessiz bir müstakil evde, yalnızca takma adıyla tanınan bir romancı bunu anlamıştı. Onun ilgi odağından uzak kalışı bilinçliydi. "Bir yıldız daha yeni bir yıldızı kıskanıyor. Bunun neresi haber?" diye yazdı.`
}
];

const COLL_EX = {
  "slit": ["There was a slit in the envelope where the letter had been torn open.", "She peered through a slit in the curtain to see who was outside.", "He made a small slit in the packaging with a knife."],
  "gill": ["Fish breathe by extracting oxygen through their gills.", "The shark's gills moved rhythmically as it swam.", "Its gills flared as the fish gasped on the deck."],
  "eerie": ["An eerie silence fell over the abandoned house.", "There was something eerie about the way the door slowly opened."],
  "hiccough": ["I always get the hiccoughs after drinking soda too fast.", "The launch went smoothly apart from one minor hiccough."],
  "burden": ["The new tax placed a heavy burden on small businesses.", "He never wanted to be a burden to his children.", "Volunteers helped ease the burden on the exhausted staff."],
  "greedy": ["The dog was greedy for more treats and kept begging.", "She was too greedy to share the prize with her teammates.", "There's plenty for everyone, so don't be greedy."],
  "curbside": ["A taxi was waiting at the curbside outside the hotel.", "The restaurant offers curbside pickup for online orders.", "Please wait at the curbside until your ride arrives."],
  "detached house": ["They bought a detached house with a garden for the kids.", "My grandparents live in a detached house on a quiet street."],
  "eyelid": ["Her eyelids grew heavy as the long lecture continued.", "A snowflake landed on his eyelid and melted instantly.", "He blinked slowly, fighting his droopy eyelids."],
  "nod": ["She gave a quick nod to show she understood.", "He nodded his head to the stranger across the room.", "I kept nodding off during the boring documentary."],
  "absence": ["In the absence of any evidence, the case was dropped.", "Her absence from the meeting was noticed by everyone.", "In the manager's absence, the assistant handled all decisions."],
  "valuable": ["This painting is extremely valuable and heavily insured.", "Your advice has been very valuable to me over the years.", "Failure taught him a valuable lesson about patience."],
  "irreplaceable": ["These old family photos are utterly irreplaceable.", "She proved to be an irreplaceable part of the team."],
  "clandestine": ["The rebels held clandestine meetings in the basement.", "He led a clandestine life that no one suspected."],
  "pseudonym / pen name": ["The author wrote all her thrillers under a pseudonym.", "\"Mark Twain\" was a pen name for Samuel Clemens."],
  "bunker": ["The soldiers built an underground bunker for protection.", "Everyone took cover in a bunker when the sirens sounded.", "His ball landed in a bunker just short of the green."],
  "exasperated": ["She was exasperated with her brother for always arriving late.", "He let out an exasperated sigh when the printer jammed again.", "I could see the teacher getting exasperated as the noise grew louder."],
  "commiserating": ["I called my friend to commiserate with her after she lost the match.", "The whole team gathered to commiserate over the loss of the contract.", "Several colleagues came by to offer their commiserations after the layoff."],
  "agitated": ["He started to get agitated when the meeting dragged on for hours.", "She was agitated about the exam results she was waiting for.", "Please calm down and don't get so agitated over a small mistake."],
  "perturbed": ["The manager was clearly perturbed by the sudden drop in sales.", "She looked deeply perturbed after reading the doctor's letter.", "He didn't seem perturbed at all by the harsh criticism."],
  "ruthless": ["She is completely ruthless in business and never backs down.", "The country suffered for years under a ruthless dictator.", "To win at any cost, he became utterly ruthless."],
  "cruel": ["It was cruel to laugh at him when he tripped in front of everyone.", "It was cruel to leave the dog out in the cold all night.", "By a cruel twist of fate, they missed the last train home."],
  "blunt": ["To be blunt, your essay simply isn't good enough yet.", "You can't cut the rope with such a blunt knife.", "The doctor was very blunt with me about my chances of recovery.", "He was surprisingly blunt about his reasons for quitting."],
  "blunder": ["The new intern made a serious blunder on his first day.", "Losing that file was a costly blunder for the company.", "Sending troops there proved to be a tactical blunder."],
  "hypocrite / hypocritical": ["They called him a hypocrite for preaching honesty while lying himself.", "It's hypocritical to criticise others for something you do yourself.", "She was being hypocritical about the whole environmental issue."],
  "contradicting": ["You keep contradicting yourself every time you tell the story.", "The witnesses kept contradicting the official statement.", "His new testimony directly contradicts what he said last week."],
  "accountable": ["We must hold politicians accountable for their promises.", "The manager is accountable for every decision the team makes.", "As team leader, she is accountable to the board of directors."],
  "rigged": ["Many voters believed the election had been rigged.", "The whole system feels rigged against ordinary workers.", "He claimed the contest was rigged after he lost."],
  "fake claims": ["The company made fake claims about how fast the product worked.", "The seller was banned for making fake claims online.", "Regulators cracked down on fake health claims in the advert."],
  "hoodwink": ["They tried to hoodwink her into signing the contract without reading it.", "Thousands of customers were hoodwinked by the fraudulent scheme.", "He hoodwinked the old man with a convincing but false story."],
  "take a leaf out of someone's book": ["You could take a leaf out of your sister's book and start saving money.", "He works so hard that you should take a leaf out of her book."],
  "get someone back for something": ["She wanted to get him back for embarrassing her at the party.", "He's always trying to get his rival back after every argument.", "I hid his keys just to get you back for the prank."],
  "start a vendetta against": ["He started a vendetta against his former partner after the deal collapsed.", "Their feud was driven by a personal vendetta that lasted for years."],
  "way below the belt": ["Mocking his dead father was way below the belt.", "The comedian went below the belt with that joke about her illness.", "You called me a liar in front of everyone; that was below the belt."],
  "think it through": ["Don't rush your answer; think it through first.", "You should take time to think it through before signing anything.", "Let me think this decision through before I commit to the move."],
  "how is that news": ["He's late again? How is that news?"],
  "deal with it": ["The train is delayed, so just deal with it.", "If you don't like the new rules, you'll have to deal with it.", "The situation is far from perfect, so deal with it."],
  "preamble": ["After a long preamble, she finally announced the winner.", "He got straight to the point and gave us the bad news without preamble.", "The preamble to the contract explains the purpose of the agreement."],
  "indulgence": ["A slice of chocolate cake is my one indulgence after a hard week.", "A hot bath at midnight is a rare indulgence for a busy mother.", "He avoids self-indulgence and rarely spends money on himself."],
  "stagnant": ["Mosquitoes breed quickly in stagnant water.", "Wages have remained stagnant for the past five years.", "The local economy became stagnant after the factory closed."],
  "detrimental": ["Too much screen time before bed is detrimental to sleep.", "Smoking has a detrimental effect on your lungs."],
  "moral fibre and merits": ["A true leader is defined by moral fibre and merits, not by wealth.", "We should judge candidates on their moral fibre and merits alone."],
  "limelight": ["The young singer suddenly found herself in the limelight.", "The star tends to hog the limelight during every interview.", "After years of training, she finally stepped into the limelight."],
  "share the limelight": ["The director was happy to share the limelight with his crew.", "The ageing actor refused to share the limelight with newcomers."],
  "tangled love lives": ["The show follows the tangled love lives of six college friends.", "Viewers love to follow their tangled love lives week after week."],
  "common ground": ["The two parties struggled to find common ground on the budget.", "She quickly discovered common ground with her new colleagues.", "Negotiators must seek common ground before any deal is possible."],
  "break even": ["The small cafe expects to break even on its first year of trading.", "It took a year to break even after opening the shop.", "The startup hopes to break even by next December."],
  "backward compatible": ["The new console is backward compatible with old games.", "The developers worked hard to make the software backward compatible."],
  "blend in": ["She quickly learned to blend in with the crowd at the new school.", "He wore plain grey clothes to blend in rather than stand out."],
  "stir": ["She slowly stirred the soup so it wouldn't stick to the pot.", "The speaker's passionate words stirred the crowd to their feet.", "The cat lay so still it did not stir even when we entered."],
  "pacemaker": ["Doctors decided to fit the elderly patient with a pacemaker.", "A pacemaker keeps the heart beating at a steady rhythm.", "My grandfather has a pacemaker and feels much healthier now."],
  "Heimlich maneuver": ["A waiter performed the Heimlich maneuver on the choking diner.", "All the lifeguards are trained in the Heimlich maneuver."],
  "charley horse": ["I got a painful charley horse during last night's football match.", "She woke up with a charley horse that made her limp all morning.", "He felt a sudden charley horse in his calf as he sprinted."],
  "suck out": ["The machine sucks out all the moisture from the air.", "The dentist sucked the saliva out with a thin tube."],
  "casualties": ["The earthquake caused heavy civilian casualties across the region.", "The army suffered severe casualties during the long battle.", "Fortunately, there were no casualties in the factory fire."],
  "death toll": ["The death toll from the flood rose to over two hundred.", "The death toll from the disease keeps climbing each week.", "Rescue teams worked hard to prevent a rising death toll."],
  "indiscriminate": ["The indiscriminate bombing of the city destroyed entire neighbourhoods.", "The attack was indiscriminate in its targets, hitting homes and hospitals alike."],
  "crippled": ["The company was crippled by mounting debt and could not recover.", "The strike crippled the economy for several weeks.", "After the accident he was left crippled and needed constant care."],
  "arsonist": ["Police arrested a suspected arsonist near the burned warehouse.", "Investigators are still trying to catch the arsonist responsible.", "An arsonist set the abandoned building ablaze late at night."],
  "cancel culture": ["The debate over cancel culture divided the entire newsroom.", "Critics argue that cancel culture silences honest discussion.", "The comedian claimed he had become a victim of cancel culture."],
  "the cost of living continued to soar": ["Throughout the year, the cost of living continued to soar.", "As the cost of living soared, many families cut back on spending."],
  "come across": ["I came across an old photo album while cleaning the attic.", "Despite his confidence, he comes across as rather shy at first."],
  "put off": ["They put off the meeting until next Thursday because of the storm.", "His rude comments really put me off working with him.", "Many customers were put off by the high prices."],
  "wind up": ["If you keep making bad choices, you'll wind up lost and alone.", "His brothers love to wind him up until he loses his temper.", "We wound up staying an extra night because of the delay."],
  "fall back on": ["When his acting career stalled, he could always fall back on teaching.", "It's comforting to have some savings to fall back on."],
  "get around to": ["I've been meaning to get around to fixing the fence all summer.", "She kept saying she'd call him back, but she never got around to it.", "After years of putting it off, he finally got around to writing his memoir."],
  "figure out": ["I can't figure out how this new coffee machine works.", "It took the engineers a week to figure out the problem with the engine.", "No matter how hard I try, I can't figure this puzzle out."],
  "point out": ["The teacher was quick to point out a mistake in my essay.", "She pointed out that the deadline had already passed.", "It's worth pointing out that the offer expires tomorrow."],
  "bring up": ["He always brings up politics at family dinners.", "After her parents died, she was brought up by her grandparents.", "Bringing up a child on your own is incredibly demanding."],
  "turn out": ["Don't worry, I'm sure everything will turn out fine.", "It turned out that the keys had been in my pocket the whole time.", "The stranger turned out to be a famous actor."],
  "carry out": ["The lab will carry out a series of tests on the water samples.", "Scientists carried out research into the new virus for months."],
  "back up": ["You need to back up your claim with solid data.", "Remember to back up your files before updating the software.", "If anyone questions the plan, I'll back you up."],
  "narrow down": ["We managed to narrow down the list of candidates to three.", "The detectives finally narrowed it down to a single cause."],
  "the elephant in the room": ["Someone finally decided to address the elephant in the room and mention the layoffs.", "The elephant in the room is that nobody wants to admit the project failed."],
  "cut corners": ["The factory was fined for cutting corners on safety.", "You simply can't cut corners when it comes to patient care."],
  "on the fence": ["I'm still on the fence about whether to accept the job offer.", "Half the committee is still on the fence."],
  "a double-edged sword": ["Social media is a double-edged sword for teenagers.", "Fame is a double-edged sword that brings both money and constant scrutiny."],
  "hit the nail on the head": ["You really hit the nail on the head with your comment about poor communication.", "When she said we were overworked, she hit the nail on the head."],
  "the tip of the iceberg": ["These complaints are just the tip of the iceberg.", "The missing funds are only the tip of the iceberg."],
  "play devil's advocate": ["Let me play devil's advocate and argue the opposite side for a moment.", "I don't really disagree; I'm just playing devil's advocate.", "Let me play devil's advocate here and ask what happens if it fails."],
  "in the long run": ["Investing in good insulation will save you money in the long run.", "Buying cheap shoes seems smart, but quality ones pay off in the long run."],
  "take something with a grain of salt": ["Take his advice with a grain of salt, since he barely knows the subject.", "You should take online reviews with a grain of salt because some are fake."],
  "get the hang of": ["It took me a week to get the hang of the new software.", "Don't worry about the controls; you'll get the hang of it soon.", "Once you get the hang of it, riding a bike feels effortless."],
  "reckon": ["I reckon that we should leave before the traffic gets bad.", "How much do you reckon this old painting is worth?", "Critics reckon the novel to be her finest work."],
  "subtle": ["There was a subtle difference between the two shades of blue.", "This wine has subtle notes of vanilla and oak.", "The change in his tone was so subtle that nobody noticed."],
  "crucial": ["Regular exercise is crucial to good health.", "Her calm attitude was crucial in resolving the dispute.", "Teachers play a crucial role in shaping young minds.", "Getting enough sleep before the exam is absolutely crucial."],
  "considerable": ["They spent a considerable amount of money on the renovation.", "She brings considerable experience to the management team."],
  "compelling": ["The lawyer made a compelling argument that convinced the jury.", "There is compelling evidence that the climate is warming.", "The film tells a compelling story about survival."],
  "deliberate": ["It was a deliberate attempt to mislead the investors.", "He spoke in a slow, deliberate manner so everyone could follow.", "Breaking the vase was no accident; it was a deliberate act."],
  "inevitable": ["After years of losses, the company's collapse was inevitable.", "It was inevitable that the two rivals would eventually clash.", "Higher prices were the inevitable outcome of the shortage."],
  "tendency": ["He has a tendency to interrupt people during meetings.", "She showed a tendency towards perfectionism at work.", "Stock prices have shown an upward tendency this month."],
  "not bat an eyelid": ["She didn't bat an eyelid when the bill arrived.", "He handed over the cash without batting an eyelid."],
  "by all accounts": ["By all accounts, the concert was an unforgettable evening.", "The launch was, by all accounts, a success."]
};
